"""Regenerate + sign the public LLM-API catalog (increment 2).

The catalog (inference APIs x models x model-card facts, joined with corpus.py
provenance) is GENERATED by the probe (`provenance-probe build-catalog`, which
fetches models.dev and joins it with corpus.py). The observatory's job is to
refresh it nightly, sign it (cosign/Rekor, via lib/signing) and publish it in
`data/` so the Pages/API layer serves a verifiable, continuously-updated artifact.

T7 contract: the probe is consumed strictly as a BLACK-BOX CLI here — this module
shells out to `provenance-probe build-catalog` and never imports probe internals.
It reads the produced JSON only to sanity-check it before signing (the same way the
runner reads verdict.json), not to reimplement any fingerprinting logic.

Difference from the registry (`build_registry.py`): the registry is DETERMINISTIC
from corpus.py, so it has a drift gate (verify-registry) and a no-change run keeps
its signature. The catalog is NON-deterministic — it tracks a live upstream
(models.dev) that changes daily — so there is no drift gate; instead a fail-closed
**well-formed + non-empty** gate makes a models.dev outage a clean no-op (never
publish an empty/garbage catalog over a good one). A byte-identical day still keeps
the committed signature.

Graceful degradation (matches signing/registry): `build-catalog` only exists in a
probe recent enough; on an older pinned probe this is a clean no-op with a reason.
"""
from __future__ import annotations

import json
import os
import subprocess

from lib import signing

CATALOG_SUBDIR = "catalog"
CATALOG_FILENAME = "catalog.json"


def _looks_unavailable(stderr: str) -> bool:
    s = (stderr or "").lower()
    return "invalid choice" in s and "build-catalog" in s


def _rm(p: str) -> None:
    try:
        os.remove(p)
    except OSError:
        pass


def _read(p: str) -> str | None:
    try:
        with open(p, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return None


def _validate(text: str | None) -> str | None:
    """Return a problem string if the generated catalog is not a well-formed,
    non-empty catalog document, else None. Fail-closed: a models.dev outage that
    somehow yields an empty/garbage file must NOT be signed and published."""
    if not text:
        return "empty output"
    try:
        doc = json.loads(text)
    except json.JSONDecodeError as e:
        return f"not valid JSON: {e}"
    if not isinstance(doc, dict):
        return "not a JSON object"
    if not doc.get("catalog_version"):
        return "missing catalog_version"
    provs = doc.get("providers")
    if not isinstance(provs, list) or not provs:
        return "no providers"
    if not isinstance(doc.get("model_count"), int) or doc["model_count"] <= 0:
        return "no models"
    return None


def build_signed_catalog(data_dir: str, *, run=subprocess.run) -> dict:
    """Regenerate the catalog via the probe CLI, gate it on a well-formed+non-empty
    check, then sign — writing to a TEMP file and only atomically promoting a
    valid+signed copy into the published path. A build/validate failure NEVER
    overwrites or publishes (the prior catalog stays put), and a `.cosign.bundle` is
    never left next to content it doesn't match. Never raises, for the runner's sake."""
    out_dir = os.path.join(data_dir, CATALOG_SUBDIR)
    os.makedirs(out_dir, exist_ok=True)
    final = os.path.join(out_dir, CATALOG_FILENAME)
    final_bundle = final + ".cosign.bundle"
    tmp = final + ".tmp"

    def _probe(*args):
        return run(["provenance-probe", *args], capture_output=True, text=True, timeout=300)

    # 1. generate to TEMP (published file untouched until valid + promoted). The
    #    probe's build-catalog exits non-zero if models.dev is unreachable, so an
    #    outage lands here, not as an empty publish.
    try:
        r = _probe("build-catalog", "--out", tmp)
    except (OSError, subprocess.SubprocessError) as e:
        _rm(tmp)
        return {"built": False, "signed": False,
                "reason": f"could not run provenance-probe: {e}", "path": final}
    if r.returncode != 0:
        _rm(tmp)
        if _looks_unavailable(r.stderr):
            return {"built": False, "signed": False,
                    "reason": "provenance-probe build-catalog unavailable (needs a newer probe; "
                              "bump the requirements pin once released)", "path": final}
        return {"built": False, "signed": False,
                "reason": f"build-catalog failed (models.dev unreachable?): "
                          f"{(r.stderr or '').strip()[:200]}", "path": final}

    # 2. fail-closed validation on the TEMP: a garbage/empty catalog is not published.
    text = _read(tmp)
    problem = _validate(text)
    if problem is not None:
        _rm(tmp)
        return {"built": True, "verified": False, "signed": False,
                "reason": f"generated catalog rejected (published copy left untouched): {problem}",
                "path": final}

    # 3. no-change fast path: models.dev didn't move today -> keep the committed
    #    catalog + its (valid) signature exactly as-is.
    if text == _read(final):
        _rm(tmp)
        return {"built": True, "verified": True, "unchanged": True,
                "signed": os.path.exists(final_bundle),
                "bundle": final_bundle if os.path.exists(final_bundle) else None,
                "reason": "unchanged; catalog already published", "path": final}

    # 4. content changed: sign the TEMP, then atomically promote. Remove the old
    #    bundle BEFORE swapping content, so a crash mid-promote leaves signed:false
    #    (honest) rather than new-bytes-beside-old-signature.
    sig = signing.sign_manifest(tmp)
    _rm(final_bundle)
    os.replace(tmp, final)
    if sig["signed"] and sig.get("bundle") and os.path.exists(sig["bundle"]):
        os.replace(sig["bundle"], final_bundle)
        bundle = final_bundle
    else:
        _rm(tmp + ".cosign.bundle")
        bundle = None
    return {"built": True, "verified": True, "signed": sig["signed"],
            "bundle": bundle, "reason": sig["reason"], "path": final}
