"""Regenerate + sign the public provider-attribution registry (increment 2).

The registry is GENERATED by the probe (`provenance-probe build-registry`, from its
`corpus.py`); the observatory's job is to sign it (cosign/Rekor, via lib/signing)
and publish it in `data/` so the Pages/API layer serves a verifiable artifact.

T7 contract: the probe is consumed strictly as a BLACK-BOX CLI here — this module
shells out to `provenance-probe build-registry` / `verify-registry` and never
imports the probe's internals.

Graceful degradation (matches signing): the `build-registry` command only exists in
probe >= 0.27.0. Until the requirements pin is bumped to a released build-registry
version, an older installed probe makes this a clean no-op with a stated reason,
never a hard failure of the nightly run.
"""
from __future__ import annotations

import os
import subprocess

from lib import signing

REGISTRY_SUBDIR = "registry"
REGISTRY_FILENAME = "registry.json"


def _looks_unavailable(stderr: str) -> bool:
    # argparse rejects an unknown subcommand with "invalid choice: 'build-registry'".
    s = (stderr or "").lower()
    return "invalid choice" in s and "build-registry" in s


def _rm(p: str) -> None:
    try:
        os.remove(p)
    except OSError:
        pass


def _read(p: str) -> str | None:
    try:
        with open(p, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return None


def build_signed_registry(data_dir: str, *, run=subprocess.run) -> dict:
    """Generate the registry via the probe CLI, gate it on verify-registry (drift),
    then sign it — writing to a TEMP file and only atomically promoting a
    verified+signed copy into the published path. A build/verify failure NEVER
    overwrites or publishes; the drift gate is fail-closed for PUBLICATION, not just
    signing, and a `.cosign.bundle` is never left next to content it doesn't match.
    Never raises, for the nightly runner's sake."""
    out_dir = os.path.join(data_dir, REGISTRY_SUBDIR)
    os.makedirs(out_dir, exist_ok=True)
    final = os.path.join(out_dir, REGISTRY_FILENAME)
    final_bundle = final + ".cosign.bundle"
    tmp = final + ".tmp"

    def _probe(*args):
        return run(["provenance-probe", *args], capture_output=True, text=True, timeout=120)

    # 1. generate to TEMP (the published file is untouched until verified + promoted).
    try:
        r = _probe("build-registry", "--out", tmp)
    except (OSError, subprocess.SubprocessError) as e:
        _rm(tmp)
        return {"built": False, "signed": False,
                "reason": f"could not run provenance-probe: {e}", "path": final}
    if r.returncode != 0:
        _rm(tmp)
        if _looks_unavailable(r.stderr):
            return {"built": False, "signed": False,
                    "reason": "provenance-probe build-registry unavailable (needs >=0.27.0; "
                              "bump the requirements pin once released)", "path": final}
        return {"built": False, "signed": False,
                "reason": f"build-registry failed: {(r.stderr or '').strip()[:200]}", "path": final}

    # 2. drift gate on the TEMP: a registry that no longer matches corpus.py is not
    #    verified, so it is never published or signed. The published copy stays put.
    v = _probe("verify-registry", tmp)
    if v.returncode != 0:
        _rm(tmp)
        return {"built": True, "verified": False, "signed": False,
                "reason": f"verify-registry failed (published copy left untouched): "
                          f"{(v.stderr or '').strip()[:200]}", "path": final}

    # 3. no-change fast path: deterministic output identical to what's published ->
    #    leave the committed registry + its (valid) signature exactly as-is.
    if _read(tmp) == _read(final):
        _rm(tmp)
        return {"built": True, "verified": True, "unchanged": True,
                "signed": os.path.exists(final_bundle),
                "bundle": final_bundle if os.path.exists(final_bundle) else None,
                "reason": "unchanged; registry already published", "path": final}

    # 4. content changed: sign the TEMP, then atomically promote. Remove the old
    #    bundle BEFORE swapping content, so a crash mid-promote leaves signed:false
    #    (honest) rather than new-bytes-beside-old-signature.
    sig = signing.sign_manifest(tmp)   # writes tmp + ".cosign.bundle" when cosign is present
    _rm(final_bundle)
    os.replace(tmp, final)
    if sig["signed"] and sig.get("bundle") and os.path.exists(sig["bundle"]):
        os.replace(sig["bundle"], final_bundle)
        bundle = final_bundle
    else:
        _rm(tmp + ".cosign.bundle")    # hygiene: drop a partial/orphan temp bundle
        bundle = None
    return {"built": True, "verified": True, "signed": sig["signed"],
            "bundle": bundle, "reason": sig["reason"], "path": final}
