"""Regenerate + sign the public SERVICE catalog (service/provider map).

Sibling to build_catalog.py. Where the model catalog (build_catalog.py) maps
inference APIs x models, THIS maps SERVICES/APPS -> operator + jurisdiction +
the backend model/provider each fronts. It is GENERATED by the probe
(`provenance-probe build-service-catalog`, which assembles it from corpus.py's
endpoint/aggregator lists + client-source findings + a curated app list). The
observatory's job is to refresh it nightly, sign it (cosign/Rekor, via lib/signing)
and publish it in `data/` so the Pages/API layer serves a verifiable artifact.

T7 contract: the probe is consumed strictly as a BLACK-BOX CLI here — this module
shells out to the CLI and never imports probe internals. It reads the produced JSON
only to sanity-check it before signing, not to reimplement any attribution logic.

INVARIANT preserved: every row is a STATIC ATTRIBUTION POINTER (measured:false),
never a measured runtime verdict — the same contract the rendered page carries.

Graceful degradation (matches build_catalog.py): `build-service-catalog` only exists
in a probe recent enough. On an older pinned probe (the command is not yet on a PyPI
release) this is a clean NO-OP with a reason — the committed seed
(data/service-catalog/service-catalog.json) stays put and is published as-is, so the
site never loses the service catalog. Bump the requirements pin once the probe
release that ships `build-service-catalog` lands, then this starts regenerating.

TODO(operator): once the probe release shipping `build-service-catalog` is pinned in
requirements.txt, confirm the nightly regenerates + signs this (watch the
[service-catalog] log line flip built=True), and drop the seed once a signed copy is
committed. Signing here mirrors the model catalog exactly (lib.signing.sign_manifest).
"""
from __future__ import annotations

import json
import os
import subprocess

from lib import signing

CATALOG_SUBDIR = "service-catalog"
CATALOG_FILENAME = "service-catalog.json"
# A change that drops service_count below this fraction of the published catalog is
# treated as a suspected partial/degraded generation and REJECTED (kept for review).
CATALOG_SHRINK_FLOOR = 0.5


def _looks_unavailable(stderr: str) -> bool:
    s = (stderr or "").lower()
    return "invalid choice" in s and "build-service-catalog" in s


def _rm(p: str) -> None:
    try:
        os.remove(p)
    except OSError:
        pass


def _read(p: str) -> str | None:
    try:
        with open(p, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return None


def _validate(text: str | None) -> str | None:
    """Return a problem string if the generated service catalog is not a well-formed,
    non-empty document, else None. Fail-closed: a garbage/empty file must NOT be signed
    and published over a good seed/catalog. Also enforces the measured:false invariant —
    a row that claims measured:true is not a static attribution pointer and is rejected."""
    if not text:
        return "empty output"
    try:
        doc = json.loads(text)
    except json.JSONDecodeError as e:
        return f"not valid JSON: {e}"
    if not isinstance(doc, dict):
        return "not a JSON object"
    if not doc.get("catalog_version"):
        return "missing catalog_version"
    svcs = doc.get("services")
    if not isinstance(svcs, list) or not svcs:
        return "no services"
    for s in svcs:
        if isinstance(s, dict) and s.get("measured") is True:
            return "invariant violated: a service row is measured:true (must be a static pointer)"
    return None


def _service_count(text: str | None) -> int:
    """service_count of a catalog text blob (falls back to len(services)), or 0."""
    try:
        doc = json.loads(text or "")
    except (json.JSONDecodeError, TypeError):
        return 0
    if not isinstance(doc, dict):
        return 0
    n = doc.get("service_count")
    if isinstance(n, int) and not isinstance(n, bool) and n > 0:
        return n
    svcs = doc.get("services")
    return len(svcs) if isinstance(svcs, list) else 0


def build_signed_service_catalog(data_dir: str, *, run=subprocess.run) -> dict:
    """Regenerate the service catalog via the probe CLI, gate it on a well-formed +
    non-empty + measured:false check, then sign — writing to a TEMP file and only
    atomically promoting a valid+signed copy. A build/validate failure NEVER overwrites
    the published copy (the committed seed stays put). Never raises, for the runner."""
    out_dir = os.path.join(data_dir, CATALOG_SUBDIR)
    os.makedirs(out_dir, exist_ok=True)
    final = os.path.join(out_dir, CATALOG_FILENAME)
    final_bundle = final + ".cosign.bundle"
    tmp = final + ".tmp"

    def _probe(*args):
        return run(["provenance-probe", *args], capture_output=True, text=True, timeout=300)

    # 1. generate to TEMP (published file/seed untouched until valid + promoted).
    try:
        r = _probe("build-service-catalog", "--out", tmp)
    except (OSError, subprocess.SubprocessError) as e:
        _rm(tmp)
        return {"built": False, "signed": False,
                "reason": f"could not run provenance-probe: {e}", "path": final}
    if r.returncode != 0:
        _rm(tmp)
        if _looks_unavailable(r.stderr):
            return {"built": False, "signed": False,
                    "reason": "provenance-probe build-service-catalog unavailable (needs a newer "
                              "probe; committed seed kept — bump the requirements pin once the "
                              "probe release ships the command)", "path": final}
        return {"built": False, "signed": False,
                "reason": f"build-service-catalog failed: {(r.stderr or '').strip()[:200]}",
                "path": final}

    # 2. fail-closed validation on the TEMP.
    text = _read(tmp)
    problem = _validate(text)
    if problem is not None:
        _rm(tmp)
        return {"built": True, "verified": False, "signed": False,
                "reason": f"generated service catalog rejected (published copy left untouched): {problem}",
                "path": final}

    # 3. no-change fast path: keep the committed catalog + its (valid) signature.
    if text == _read(final):
        _rm(tmp)
        return {"built": True, "verified": True, "unchanged": True,
                "signed": os.path.exists(final_bundle),
                "bundle": final_bundle if os.path.exists(final_bundle) else None,
                "reason": "unchanged; service catalog already published", "path": final}

    # 3b. shrink floor: a sharply smaller catalog is a suspected partial generation.
    prior_count = _service_count(_read(final))
    new_count = _service_count(text)
    if prior_count > 0 and new_count < prior_count * CATALOG_SHRINK_FLOOR:
        _rm(tmp)
        return {"built": True, "verified": False, "signed": False,
                "reason": f"service catalog shrank {prior_count}->{new_count} services "
                          f"(below {int(CATALOG_SHRINK_FLOOR * 100)}% of published; kept prior, needs review)",
                "path": final}

    # 4. content changed: sign the TEMP, then atomically promote.
    sig = signing.sign_manifest(tmp)
    _rm(final_bundle)
    os.replace(tmp, final)
    if sig["signed"] and sig.get("bundle") and os.path.exists(sig["bundle"]):
        os.replace(sig["bundle"], final_bundle)
        bundle = final_bundle
    else:
        _rm(tmp + ".cosign.bundle")
        bundle = None
    return {"built": True, "verified": True, "signed": sig["signed"],
            "bundle": bundle, "reason": sig["reason"], "path": final}
